#!/system/bin/sh

# In TH3ORY
# enable sysctl tweaks

sysctl -p /system/etc/systctl.conf

SAMPLING_RATE=$(busybox expr `cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_transition_latency` \* 750 / 1200)
echo 80 > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold
echo 80 > /sys/devices/system/cpu/cpufreq/interactive/go_highspeed_load
echo $SAMPLING_RATE > /sys/devices/system/cpu/cpu0/cpufreq/ondemand/sampling_rate


# Start crond
echo "root:x:0:0::data/cron:/system/xbin/bash" > /system/etc/passwd
mount -o remount,rw rootfs /
ln -s /system/xbin /xbin
mount -o remount,ro rootfs /
timezone=`date +%z`
if [ $timezone = "-0800" ]; then
TZ=PST8PDT
elif [ $timezone = "-0700" ]; then
TZ=MST7MDT
elif [ $timezone = "-0600" ]; then
TZ=CST6CDT
elif [ $timezone = "-0500" ]; then
TZ=EST5EDT
else TZ=EST5EDT
fi
export TZ
crond -c /data/cron


# disable logger - performance boost & save memory (comment and reboot for logcat)
rm /dev/log/main


# Optimize
fi

if [ -e /proc/sys/vm/vfs_cache_pressure ]; then
	echo "10" > /proc/sys/vm/vfs_cache_pressure
fi

if [ -e /proc/sys/vm/dirty_expire_centisecs ]; then
	echo "500" > /proc/sys/vm/dirty_expire_centisecs
fi

if [ -e /proc/sys/vm/dirty_writeback_centisecs ]; then
	echo "1000" > /proc/sys/vm/dirty_writeback_centisecs
fi

if [ -e /proc/sys/vm/dirty_ratio ]; then
	echo "90" > /proc/sys/vm/dirty_ratio
fi

if [ -e /proc/sys/vm/dirty_background_ratio ]; then
	echo "5" > /proc/sys/vm/dirty_background_ratio
fi

if [ -f "\$i" ]; then
	sync;
	echo "cfq" > \$i;
fi

# file system speedups
busybox mount -o remount,noatime,barrier=0,nobh /cache


# Kernel Tweaks
#
sysctl -w kernel.sched_features=15834233;
sysctl -w kernel.panic=0;
sysctl -w kernel.panic_on_oops=1;
#sysctl -w kernel.msgmni=2048;
#sysctl -w kernel.msgmax=64000;
#sysctl -w kernel.shmmax=268435500;
#sysctl -w kernel.sem=500,512000,64,2048;
#sysctl -w kernel.hung_task_timeout_secs=0;
sysctl -w kernel.sched_latency_ns=5000000; #600000
sysctl -w kernel.sched_min_granularity_ns=1000000; #400000
sysctl -w kernel.sched_wakeup_granularity_ns=1000000;
sysctl -w kernel.sched_compat_yield=1;
#sysctl -w kernel.sched_shares_ratelimit=256000;
sysctl -w kernel.sched_child_runs_first=0;
#sysctl -w kernel.threads-max=525810;
#sysctl -w kernel.multi_threading=2;

#HyperTh3ory
#
rm -f /cache/*.apk
rm -f /cache/*.tmp
rm -f /data/dalvik-cache/*.apk
rm -f /data/dalvik-cache/*.tmp
busybox mount -o remount,rw,noatime,noauto_da_alloc,nodiratime,barrier=0,nobh /system
busybox mount -o remount,noatime,noauto_da_alloc,nodiratime,nodev,barrier=0,nobh /data
busybox mount -o remount,noatime,noauto_da_all
sysctl -w vm.overcommit_memory=1
sysctl -w vm.page-cluster=3
sysctl -w vm.drop_caches=3

#Database
#
for i in \ `find /data -iname "*.db"` do \ sqlite3 $i 'VACUUM;'; done

#Battery
#
busybox sysctl -w vm.dirty_expire_centisecs=1000;
busybox sysctl -w vm.dirty_writeback_centisecs=2000;
sysctl -w kernel.random.write_wakeup_threshold=256
sysctl -w kernel.random.read_wakeup_threshold=128


# sd card speed boost
if [ -e /sys/devices/virtual/bdi/179:0/read_ahead_kb ]; then
  echo 2048 > /sys/devices/virtual/bdi/179:0/read_ahead_kb
fi
